source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

pod 'MMDrawerController', '~> 0.5.7'
pod 'OLGhostAlertView', '~> 1.8.1'
pod 'HockeySDK', '~> 3.6'

pod "hybrisMobileCommerceLibrary", :path => "../hybrisMobileCommerceLibrary"
pod "hybrisMobileLocationLibrary", :path => "../hybrisMobileLocationLibrary"

target :Specs, :exclusive => true do
    pod 'Specta', '~> 0.3'
    pod 'Expecta', '~> 0.3'
end

post_install do | installer |
    installer.project.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
end
