source 'https://github.com/CocoaPods/Specs.git'

target 'hybrisMobileCommerceLibrary', :exclusive => true do
  pod "hybrisMobileCommerceLibrary", :path => "../"
  pod 'AFNetworking', '~> 2.5'
end

target 'Specs', :exclusive => true do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end